import * as THREE from './vendor/three.module.min.js';
import {SoftwareRenderer} from './software-renderer.js';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=THREE.MathUtils.lerp;
const ui={};for(const id of ['score','multiplier','timer','distance','speed','gear','rpmFill','nitroFill','nitroText','checkpointDistance','checkpointProgress','health','zone','toast','flash','speedFX'])ui[id]=$(id);
let best=0;try{best=Number(localStorage.getItem('erko-rider-best'))||0}catch{}$('menuBest').textContent=best.toLocaleString();
const state={mode:'menu',speed:0,x:1.8,vx:0,distance:0,score:0,time:45,nitro:100,health:100,near:0,maxSpeed:0,mult:1,highTime:0,nextCP:1400,checkpoint:0,invuln:0,shake:0,boost:false,drift:0,gear:0,rpm:900,wide:false};
const input={gas:false,brake:false,left:false,right:false,nitro:false};let elapsed=0,toastTime=0,lastGear=0,frameMS=16;const coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;const mobileUI=()=>coarse||innerWidth<950;
let renderer,software=false;try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){software=true;const c=$('game').cloneNode();$('game').replaceWith(c);renderer=new SoftwareRenderer({canvas:c});}
renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.4:1.6));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x090f20);scene.fog=new THREE.FogExp2(0x10182b,.0048);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,1400);
scene.add(new THREE.HemisphereLight(0xb2d2ff,0x182031,2.6));const moonLight=new THREE.DirectionalLight(0x9dc2ff,3.5);moonLight.position.set(-30,50,20);scene.add(moonLight);const rim=new THREE.DirectionalLight(0xffbea1,1.6);rim.position.set(20,15,-20);scene.add(rim);
// A tiny studio environment produces genuine, inexpensive paint reflections.
const envScene=new THREE.Scene();envScene.background=new THREE.Color(0x161d2b);for(let i=0;i<6;i++){const p=new THREE.Mesh(new THREE.PlaneGeometry(18,3),new THREE.MeshBasicMaterial({color:i%2?0x8096bf:0xe1edff,side:THREE.DoubleSide}));p.position.set(Math.sin(i)*12,3+i*2,Math.cos(i)*12);p.lookAt(0,0,0);envScene.add(p)}if(!software){const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromScene(envScene,.04);scene.environment=env.texture;pmrem.dispose();}
const mat=(color,roughness=.55,metalness=.1)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const black=new THREE.MeshPhysicalMaterial({color:0x07090d,metalness:.86,roughness:.23,clearcoat:1,clearcoatRoughness:.13,envMapIntensity:1.6});const glass=new THREE.MeshPhysicalMaterial({color:0x102032,metalness:.8,roughness:.15,clearcoat:1});const rubber=mat(0x090b10,.85),alloy=mat(0x333c48,.23,.9),trim=mat(0x0a0b0f,.45,.65);const red=new THREE.MeshBasicMaterial({color:0xff1839}),white=new THREE.MeshBasicMaterial({color:0xd7eeff}),gold=new THREE.MeshBasicMaterial({color:0xb9dbff}),cyan=new THREE.MeshBasicMaterial({color:0x78dfff}),amber=new THREE.MeshBasicMaterial({color:0xffa737});
const boxGeo=new THREE.BoxGeometry(1,1,1);function box(parent,m,x,y,z,w,h,d){const o=new THREE.Mesh(boxGeo,m);o.position.set(x,y,z);o.scale.set(w,h,d);parent.add(o);return o}
function skin(sections,material,parent){const v=[],idx=[];for(const [z,width,low,shoulder,top] of sections){v.push(-width,low,z,-width,shoulder,z,-width*.78,top,z,width*.78,top,z,width,shoulder,z,width,low,z)}for(let j=0;j<sections.length-1;j++)for(let i=0;i<6;i++){const a=j*6+i,b=j*6+(i+1)%6,c=a+6,d=b+6;idx.push(a,c,b,b,c,d)}idx.push(0,1,2,0,2,3,0,3,4,0,4,5);let b=(sections.length-1)*6;idx.push(b,b+2,b+1,b,b+3,b+2,b,b+4,b+3,b,b+5,b+4);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const mesh=new THREE.Mesh(g,material);parent.add(mesh);return mesh}
const wheelTire=new THREE.CylinderGeometry(.355,.355,.24,20),wheelRim=new THREE.CylinderGeometry(.26,.26,.251,10),discGeo=new THREE.CylinderGeometry(.18,.18,.26,16);
function wheel(parent,x,z,hero=false){const pivot=new THREE.Group();pivot.position.set(x,.38,z);parent.add(pivot);const spin=new THREE.Group();pivot.add(spin);for(const [g,m]of[[wheelTire,rubber],[wheelRim,alloy]]){const o=new THREE.Mesh(g,m);o.rotation.z=Math.PI/2;spin.add(o)}if(hero){const d=new THREE.Mesh(discGeo,trim);d.rotation.z=Math.PI/2;spin.add(d);for(let j=0;j<5;j++){const spoke=box(spin,alloy,x>0?.132:-.132,0,0,.018,.47,.038);spoke.rotation.x=j*Math.PI/5;}}return{pivot,spin,front:z<0}}
function labelTexture(text,fg='#dae2ec',bg='#111722',w=512,h=128,font='bold 64px Arial'){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=font;ctx.fillStyle=fg;ctx.fillText(text,w/2,h/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function makeCar(type=0,hero=false,color=0x566577){const root=new THREE.Group(),body=new THREE.Group();root.add(body);const paint=hero?black:mat(color,.32,.6);const length=type===4?7.5:type===3?5.2:type===1?3.8:4.7,width=type===4?1.19:1.0;const wheels=[];
if(hero){skin([[-2.45,.87,.30,.62,.69],[-2.13,.99,.27,.78,.91],[-1.42,1.03,.28,.86,.99],[-.38,.96,.29,.84,.97],[.7,1.05,.29,.91,1.03],[1.60,1.08,.28,.88,.99],[2.31,1.0,.32,.76,.89]],paint,body);skin([[-.75,.78,.89,.98,1.02],[-.08,.70,.95,1.42,1.47],[.72,.72,.99,1.44,1.49],[1.64,.80,.94,1.01,1.02]],glass,body);skin([[-.12,.71,1.41,1.44,1.49],[.65,.73,1.43,1.47,1.52],[.87,.74,1.35,1.41,1.45]],paint,body);
for(const s of[-1,1]){box(body,paint,s*.95,.36,0,.12,.16,3.7);box(body,trim,s*.54,.985,-1.37,.24,.017,.54);box(body,paint,s*1.095,1.01,-.40,.30,.15,.23);box(body,alloy,s*.965,.84,.37,.018,.045,.23);box(body,paint,s*.75,1.22,.61,.047,.51,.09).rotation.x=.04;for(let i=0;i<3;i++){const l=box(body,red,s*(.50+i*.155),.737,2.324,.095,.28,.033);l.rotation.z=-s*.10}box(body,white,s*.66,.69,-2.425,.48,.065,.025);for(let i=0;i<3;i++){const light=box(body,white,s*(.50+i*.125),.60,-2.43,.045,.16,.022);light.rotation.z=s*.22}box(body,trim,s*.86,.40,-2.36,.26,.20,.1);for(let j=0;j<2;j++){const tip=new THREE.Mesh(new THREE.CylinderGeometry(.081,.081,.19,10),alloy);tip.rotation.x=Math.PI/2;tip.position.set(s*(.64+j*.19),.32,2.33);body.add(tip)}}
box(body,trim,0,.62,-2.453,1.05,.24,.05);box(body,alloy,0,.64,-2.486,.20,.048,.022);box(body,trim,0,.63,2.333,1.85,.34,.02); // light panel must sit behind the tri-bars
for(const s of[-1,1])for(let i=0;i<3;i++)box(body,red,s*(.50+i*.155),.737,2.355,.095,.28,.033).rotation.z=-s*.10;
box(body,trim,0,.29,2.28,1.6,.18,.23);box(body,paint,0,.99,2.0,2.08,.065,.30);for(const x of[-.67,.67])box(body,trim,x,.94,1.95,.08,.12,.16);
const plate=new THREE.Mesh(new THREE.PlaneGeometry(.52,.15),new THREE.MeshBasicMaterial({map:labelTexture('ERKO','white','#11151d',256,64,'bold 35px Arial')}));plate.position.set(0,.48,2.359);body.add(plate);const badge=new THREE.Mesh(new THREE.CircleGeometry(.10,24),alloy);badge.position.set(0,.75,2.36);body.add(badge);
const hood=new THREE.Mesh(new THREE.PlaneGeometry(.68,.32),new THREE.MeshBasicMaterial({map:labelTexture('Erko art','#d7b764','#080b10',512,256,'italic bold 78px Georgia')}));hood.rotation.x=-Math.PI/2;hood.position.set(0,.987,-1.20);body.add(hood);
}else{skin([[-length/2,width*.86,.28,.63,.78],[-length*.32,width,.25,.83,.95],[length*.30,width,.25,.84,.93],[length/2,width*.88,.28,.7,.83]],paint,body);const high=type===2?1.85:type===3?2.25:1.5;if(type===4){box(body,paint,0,1.1,-2.55,2.35,1.9,1.9);box(body,glass,0,1.65,-3.515,2.02,.67,.025);box(body,mat(0x6e8593,.68,.25),0,1.85,.85,2.45,2.65,5.3);for(const x of[-1.17,1.17])box(body,white,x,1.92,3.51,.06,2.3,.025);}else skin([[-length*.24,.83,.86,.94,1.0],[-length*.08,.75,.9,high-.03,high],[length*.23,.77,.91,high-.06,high],[length*.37,.84,.9,1.03,1.08]],glass,body);if(type===3)box(body,paint,0,1.45,.47,1.85,1.42,2.90);for(const x of[-.78,.78]){box(body,red,x,.68,length/2+.012,.28,.15,.025);box(body,white,x,.62,-length/2-.012,.3,.12,.025)}}
for(const z of[-length*.31,length*.31])for(const s of[-1,1])wheels.push(wheel(root,s*(hero?1.01:width),z,hero));const brakeMaterials=[];if(hero)body.traverse(o=>{if(o.isMesh&&o.material===red){o.material=red.clone();brakeMaterials.push(o.material)}});root.userData={body,wheels,length,width,type,brakeMaterials};return root}
const player=makeCar(0,true);scene.add(player);player.position.x=state.x;
// Soft glow cards simulate light scattering and wet pools without full-screen postprocessing.
const gc=document.createElement('canvas');gc.width=gc.height=128;const gx=gc.getContext('2d'),gradient=gx.createRadialGradient(64,64,1,64,64,64);gradient.addColorStop(0,'rgba(255,255,255,.85)');gradient.addColorStop(.22,'rgba(255,255,255,.35)');gradient.addColorStop(1,'rgba(255,255,255,0)');gx.fillStyle=gradient;gx.fillRect(0,0,128,128);const glowTex=new THREE.CanvasTexture(gc);
function glow(parent,color,x,y,z,sx,sz,opacity=.3){const m=new THREE.MeshBasicMaterial({map:glowTex,color,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending});const o=new THREE.Mesh(new THREE.PlaneGeometry(1,1),m);o.rotation.x=-Math.PI/2;o.position.set(x,y,z);o.scale.set(sx,sz,1);parent.add(o);return o}
const tailGlow=glow(player,0xff1238,0,.035,3,4.5,7,.38);const headGlow=glow(player,0xbde5ff,0,.03,-13,10,27,.33);const nitroGlow=glow(player,0x32caff,0,.045,3,4,8,0);for(const s of[-1,1]){const sp=new THREE.SpotLight(0xc2deff,30,68,.29,.65,1);sp.position.set(s*.76,.7,-2.1);sp.target.position.set(s*.9,.1,-38);player.add(sp,sp.target)}
const exhaust=[];for(const s of[-1,1]){const flame=new THREE.Mesh(new THREE.ConeGeometry(.16,1.2,9),new THREE.MeshBasicMaterial({color:0x79d8ff,transparent:true,opacity:.9}));flame.rotation.x=Math.PI/2;flame.position.set(s*.74,.32,2.8);player.add(flame);exhaust.push(flame)}
const roadCanvas=document.createElement('canvas');roadCanvas.width=roadCanvas.height=256;const rc=roadCanvas.getContext('2d');rc.fillStyle='#252d3b';rc.fillRect(0,0,256,256);let seed=1307;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}for(let i=0;i<9000;i++){const n=30+rand()*40;rc.fillStyle=`rgba(${n},${n+6},${n+12},.28)`;rc.fillRect(rand()*256,rand()*256,.5+rand()*2,2+rand()*9)}const roadTex=new THREE.CanvasTexture(roadCanvas);roadTex.wrapS=roadTex.wrapT=THREE.RepeatWrapping;roadTex.repeat.set(2,12);roadTex.anisotropy=4;const roadMat=new THREE.MeshStandardMaterial({map:roadTex,color:0x8495a8,metalness:.48,roughness:.3});
const ground=box(scene,mat(0x0a131b,.95),0,-.21,-300,2500,.25,2000);const road=box(scene,roadMat,0,-.09,-350,16,.16,1100);const shoulder=mat(0x34404d,.65),railMat=mat(0x718496,.33,.8),postMat=mat(0x243343,.6,.6),markMat=mat(0xc1d1df,.7),cityMat=mat(0x162335,.6),leafMat=mat(0x102521,.9),lightWindow=new THREE.MeshBasicMaterial({color:0x91b6cc}),warmWindow=new THREE.MeshBasicMaterial({color:0xd4a473});
const dummy=new THREE.Object3D();function batch(parent,material,items,geo=boxGeo){const mesh=new THREE.InstancedMesh(geo,material,items.length);items.forEach((p,i)=>{dummy.position.set(p[0],p[1],p[2]);dummy.scale.set(p[3],p[4],p[5]);dummy.rotation.set(0,p[6]||0,0);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix)});mesh.computeBoundingSphere();parent.add(mesh);return mesh}
const segments=[],segLength=90,segCount=14;const cone=new THREE.ConeGeometry(1,1,6);for(let k=0;k<segCount;k++){const group=new THREE.Group(),rails=[],posts=[],marks=[],lamps=[],buildings=[],windows=[],trees=[],earth=[];for(const s of[-1,1]){rails.push([s*8.45,.62,-45,.17,.19,90],[s*8.45,.88,-45,.13,.16,90]);earth.push([s*8.13,.01,-45,.3,.045,90]);marks.push([s*7.65,.02,-45,.10,.025,90]);for(let z=0;z<90;z+=7.5)posts.push([s*8.45,.46,-z,.10,.9,.1]);for(let z=8;z<90;z+=45){posts.push([s*9.0,5.1,-z,.17,10.2,.17],[s*7.7,10.1,-z,2.8,.13,.14]);lamps.push([s*6.7,10,-z,1.5,.045,.32]);glow(group,0x86bada,s*5,.026,-z,11,19,.13);}
for(let j=0;j<5;j++){const x=s*(24+rand()*80),z=-rand()*90,h=12+rand()*65,w=6+rand()*13,d=7+rand()*8;buildings.push([x,h/2,z,w,h,d]);for(let r=2;r<h;r+=3.9)for(let c=-w/2+1;c<w/2;c+=2.8)if(rand()>.43)windows.push([x+c,r,z+d/2+.01,.65,.9,.025]);}for(let j=0;j<10;j++)trees.push([s*(12+rand()*15),2.3,-rand()*90,1.2+rand()*1.5,4+rand()*3,1.3+rand()]);}
for(const x of[-3.6,0,3.6])for(let z=0;z<90;z+=12)marks.push([x,.022,-z,.11,.028,4.5]);batch(group,railMat,rails);batch(group,postMat,posts);batch(group,markMat,marks);batch(group,white,lamps);batch(group,cityMat,buildings);batch(group,k%2?lightWindow:warmWindow,windows);batch(group,leafMat,trees,cone);batch(group,shoulder,earth);
if(k%4===2){box(group,postMat,0,7,-50,44,1.2,9);for(const s of[-1,1])box(group,postMat,s*11,3.6,-50,1.6,7,3);box(group,railMat,0,8,-46,42,.3,.2)}if(k===6||k===7){box(group,mat(0x283140,.72),0,8.1,-45,21,1.1,90);for(const s of[-1,1]){box(group,postMat,s*9.5,4,-45,1.5,8,90);box(group,cyan,s*8.7,2.3,-45,.05,.10,90)}for(let z=0;z<90;z+=18)box(group,white,0,7.50,-z,6,.02,.14)}
if(k%3===0){box(group,railMat,0,8.1,-36,18,.18,.18);for(const s of[-1,1])box(group,postMat,s*8.8,4,-36,.22,8,.22);const names=['DOWNTOWN  ↑','PORT DISTRICT  ↑','NORTH TUNNEL  ↑','AFTER HOURS  ↑'];const sign=new THREE.Mesh(new THREE.PlaneGeometry(6.8,1.8),new THREE.MeshBasicMaterial({map:labelTexture(names[(k/3)%4|0],'#d8efee','#174644',1024,256,'bold 65px Arial')}));sign.position.set(0,7.5,-35.85);group.add(sign)}group.position.z=90-k*90;segments.push(group);scene.add(group)}
const stars=[];for(let i=0;i<350;i++)stars.push((rand()-.5)*1600,80+rand()*380,-200-rand()*700);const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xb8d5ff,size:.65,transparent:true,opacity:.6})));const moon=new THREE.Mesh(new THREE.SphereGeometry(8,24,16),new THREE.MeshBasicMaterial({color:0xadc3d8}));moon.position.set(-180,180,-750);scene.add(moon);
// A bounded pool of vehicles and particles is recycled for the entire run.
const lanes=[-5.4,-1.8,1.8,5.4],traffic=[],colors=[0x345a72,0x65717b,0x743b42,0x988a74,0x385452,0xa5a6a1];for(let i=0;i<18;i++){const car=makeCar(i%5,false,colors[i%6]);car.visible=false;scene.add(car);traffic.push({car,lane:0,target:0,speed:23,z:0,active:false,passed:false,signal:0,cooldown:5+rand()*10,indicator:box(car,amber,1,.8,car.userData.length/2+.04,.15,.12,.04)});}
const particleGeometry=new THREE.SphereGeometry(1,5,4),particles=[];for(let i=0;i<95;i++){const mesh=new THREE.Mesh(particleGeometry,new THREE.MeshBasicMaterial({color:0x7891a4,transparent:true,opacity:.2,depthWrite:false}));mesh.visible=false;scene.add(mesh);particles.push({mesh,life:0,vx:0,vy:0,vz:0,max:1})}let pi=0;function emit(x,y,z,kind){const p=particles[pi++%particles.length];p.mesh.position.set(x,y,z);p.mesh.visible=true;p.life=p.max=kind==='spark'?.35+rand()*.45:.5+rand()*.4;p.vx=(rand()-.5)*(kind==='spark'?13:1);p.vy=kind==='spark'?2+rand()*4:.4;p.vz=2+rand()*4;p.kind=kind;p.mesh.material.color.set(kind==='spark'?0xffbd55:kind==='boost'?0x52ccff:0x81909f);p.mesh.scale.setScalar(kind==='spark'?.045:kind==='boost'?.09:.13);}
const gate=new THREE.Group();for(const s of[-1,1]){box(gate,cyan,s*8.0,3.5,0,.12,7,.13);glow(gate,0x43dfff,s*7,.04,0,5,10,.35)}box(gate,cyan,0,7,0,16,.10,.13);const cpSign=new THREE.Mesh(new THREE.PlaneGeometry(7,1.1),new THREE.MeshBasicMaterial({map:labelTexture('CHECKPOINT  +25 SEC','#d9ff43','#101c2e',1024,128,'bold 62px Arial')}));cpSign.position.set(0,7.8,0);gate.add(cpSign);scene.add(gate);
// Procedural audio. Everything starts exclusively after an interaction.
let audio=null,soundOn=true;function initAudio(){if(audio){audio.ctx.resume();return}try{const ctx=new(window.AudioContext||window.webkitAudioContext)(),master=ctx.createGain();master.gain.value=soundOn?.42:0;master.connect(ctx.destination);const engine=ctx.createGain();engine.gain.value=.16;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=600;engine.connect(filter);filter.connect(master);const oscs=[];for(let i=0;i<3;i++){const o=ctx.createOscillator();o.type=i?'sawtooth':'triangle';o.frequency.value=45+i*1.5;o.connect(engine);o.start();oscs.push(o)}const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const d=buffer.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){last=(last+(Math.random()*2-1)*.12)/1.12;d[i]=last*3}const noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;const wind=ctx.createGain();wind.gain.value=0;noise.connect(wind);wind.connect(master);noise.start();const squeal=ctx.createOscillator(),squealGain=ctx.createGain();squeal.type='sawtooth';squeal.frequency.value=630;squealGain.gain.value=0;squeal.connect(squealGain);squealGain.connect(master);squeal.start();audio={ctx,master,engine,filter,oscs,wind,squealGain,buffer,step:0,nextBeat:ctx.currentTime};}catch{soundOn=false;$('soundBtn').textContent='SOUND OFF'}}
function tone(freq,dur=.12,vol=.06,type='sine'){if(!audio)return;const {ctx,master}=audio,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g);g.connect(master);o.start();o.stop(ctx.currentTime+dur);o.onended=()=>{o.disconnect();g.disconnect()}}
function impactSound(){if(!audio)return;const {ctx,master,buffer}=audio,n=ctx.createBufferSource(),g=ctx.createGain();n.buffer=buffer;g.gain.setValueAtTime(.9,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.55);n.connect(g);g.connect(master);n.start();n.stop(ctx.currentTime+.55);n.onended=()=>{n.disconnect();g.disconnect()};tone(42,.35,.55,'triangle')}
function updateAudio(){if(!audio)return;const {ctx}=audio,running=state.mode==='playing';audio.engine.gain.setTargetAtTime(running?.115+(input.gas?.045:0):.018,ctx.currentTime,.1);audio.oscs.forEach((o,i)=>o.frequency.setTargetAtTime((state.rpm/60)*(i===0?.5:i===1?1:1.01),ctx.currentTime,.04));audio.filter.frequency.setTargetAtTime(200+state.rpm*.13,ctx.currentTime,.08);audio.wind.gain.setTargetAtTime(running?Math.abs(state.speed)/100*.22+(state.boost?.22:0):0,ctx.currentTime,.15);audio.squealGain.gain.setTargetAtTime(running?state.drift*.03:0,ctx.currentTime,.08);if(running&&ctx.currentTime>=audio.nextBeat){const notes=[55,55,82.41,55,65.41,65.41,49,73.42];tone(notes[audio.step%8],.22,.055,'triangle');if(audio.step%2===0)tone(45,.13,.09);if(audio.step%4===3)tone(notes[audio.step%8]*4,.28,.025,'sine');audio.step++;audio.nextBeat=ctx.currentTime+.26;}}
function toast(text){ui.toast.textContent=text;toastTime=1.8;ui.toast.style.opacity=1}
function clearInput(){for(const k in input)input[k]=false;document.querySelectorAll('.held').forEach(e=>e.classList.remove('held'))}
function showMode(mode){state.mode=mode;for(const [id,match]of[['menu','menu'],['hud','playing'],['pause','paused'],['over','over']])$(id).hidden=mode!==match;$('touch').hidden=!(mobileUI()&&mode==='playing');$('pauseBtn').hidden=mode!=='playing';clearInput();}
function reset(){initAudio();Object.assign(state,{speed:20,x:1.8,vx:0,distance:0,score:0,time:45,nitro:100,health:100,near:0,maxSpeed:0,mult:1,highTime:0,nextCP:1400,checkpoint:0,invuln:0,shake:0,boost:false,drift:0,gear:1,rpm:2200});for(let i=0;i<segments.length;i++)segments[i].position.z=90-i*90;traffic.forEach((t,i)=>{t.active=i<9;t.car.visible=t.active;t.lane=i%4;t.target=lanes[t.lane];t.car.position.x=t.target;t.z=-150-i*65;t.speed=19+rand()*14;t.passed=false;t.signal=0;t.cooldown=7+rand()*12;});particles.forEach(p=>{p.life=0;p.mesh.visible=false});player.position.set(1.8,0,0);camera.position.set(1.8,3.2,8.4);lastGear=1;showMode('playing');toast('GO. OWN THE NIGHT.');tone(330,.20,.1);}
function end(reason){state.boost=false;const total=Math.floor(state.score);best=Math.max(best,total);try{localStorage.setItem('erko-rider-best',String(best))}catch{}$('finalScore').textContent=total.toLocaleString();$('finalDistance').textContent=(state.distance/1000).toFixed(2)+' km';$('finalSpeed').textContent=Math.round(state.maxSpeed)+' km/h';$('finalNear').textContent=state.near;$('finalBest').textContent=best.toLocaleString();$('menuBest').textContent=best.toLocaleString();$('endReason').textContent=reason;showMode('over');tone(82,.6,.18,'triangle')}
function hit(damage,side){if(state.invuln>0)return;state.health=Math.max(0,state.health-damage);state.invuln=1.65;state.shake=.65;state.speed*=.42;state.vx=side*3;state.highTime=0;impactSound();for(let i=0;i<24;i++)emit(state.x+side*.9,.65,-1,'spark');toast(state.health<=0?'WRECKED':'IMPACT — KEEP GOING');if(state.health<=0)end('WRECKED / RUN COMPLETE')}
function respawn(t){const density=Math.min(18,9+Math.floor(state.distance/800)),index=traffic.indexOf(t);t.active=index<density;t.car.visible=t.active;if(!t.active)return;let lane=(rand()*4)|0,z=-420-rand()*250;for(let j=0;j<8;j++){if(!traffic.some(o=>o!==t&&o.active&&Math.abs(o.z-z)<32&&o.lane===lane))break;z-=40;lane=(lane+1)%4}t.lane=lane;t.target=lanes[lane];t.car.position.x=t.target;t.z=z;t.speed=19+rand()*17;t.passed=false;t.signal=0;t.cooldown=7+rand()*14;}
let trafficCheck=0;function physics(dt){if(state.mode!=='playing')return;const previousSpeed=state.speed;state.boost=input.nitro&&state.nitro>1&&state.speed>8&&!input.brake;let acceleration=input.gas?11.7*(1-Math.max(state.speed,0)/100):(-1.7-state.speed*.023);if(input.brake)acceleration=state.speed>1?-23:state.speed>-4?-3:0;if(state.boost)acceleration+=16;if(!state.boost&&state.speed>73)acceleration-=12;state.speed=clamp(state.speed+acceleration*dt,-4,91);if(!state.boost&&state.speed>73&&previousSpeed<=73)state.speed=73;if(!input.gas&&!input.brake&&Math.abs(state.speed)<.25)state.speed=0;state.nitro=clamp(state.nitro+(state.boost?-23:5.5)*dt,0,100);
const steer=(input.right?1:0)-(input.left?1:0),targetV=steer*(1.2+Math.min(Math.abs(state.speed),70)*.095)*Math.sign(state.speed);state.vx=lerp(state.vx,targetV,1-Math.exp(-dt*(steer?5.5:7.5)));state.x+=state.vx*dt;state.drift=lerp(state.drift,Math.abs(steer)&&state.speed>43?clamp((state.speed-43)/30,0,1):0,dt*5);if(Math.abs(state.x)>6.85){state.x=clamp(state.x,-6.85,6.85);if(Math.abs(state.vx)>2.2&&state.speed>15)hit(state.speed>60?28:17,-Math.sign(state.x));state.vx*=-.3;}
const travel=state.speed*dt;state.distance=Math.max(0,state.distance+travel);state.time-=dt;state.highTime=state.speed>50?state.highTime+dt:Math.max(0,state.highTime-dt*2);state.mult=1+Math.min(4,Math.floor(state.highTime/4))*.5;state.score+=Math.max(0,travel)*state.mult;state.maxSpeed=Math.max(state.maxSpeed,state.speed*3.6);state.invuln=Math.max(0,state.invuln-dt);state.shake=Math.max(0,state.shake-dt);if(state.distance>=state.nextCP){state.time+=Math.max(18,25-state.checkpoint*.6);state.nextCP+=1400;state.checkpoint++;state.nitro=Math.min(100,state.nitro+25);state.score+=1000;toast('CHECKPOINT  +'+Math.max(18,25-(state.checkpoint-1)*.6).toFixed(0)+' SEC\n+1,000 POINTS');tone(660,.2,.13);}
segments.forEach(s=>{s.position.z+=travel;if(s.position.z>180)s.position.z-=segLength*segCount;if(s.position.z<-(segCount-2)*segLength)s.position.z+=segLength*segCount});roadTex.offset.y-=travel/90;
trafficCheck+=dt;for(const t of traffic){if(!t.active){if(trafficCheck>2)respawn(t);continue}const oldZ=t.z;t.z+=(state.speed-t.speed)*dt;if(t.z>35||t.z<-850){respawn(t);continue}t.cooldown-=dt;if(t.cooldown<0&&t.z < -Math.max(100,(state.speed-t.speed)*5)&&t.z>-350&&!t.signal){const lane=clamp(t.lane+(rand()>.5?1:-1),0,3);if(lane!==t.lane&&!traffic.some(o=>o!==t&&o.active&&(o.lane===lane||o.target===lanes[lane])&&Math.abs(o.z-t.z)<50)){t.signal=2;t.nextLane=lane;}t.cooldown=8+rand()*12}if(t.signal>0){t.signal-=dt;if(t.signal<=0&&t.z < -Math.max(55,(state.speed-t.speed)*2.5)&&!traffic.some(o=>o!==t&&o.active&&o.lane===t.nextLane&&Math.abs(o.z-t.z)<40)){t.lane=t.nextLane;t.target=lanes[t.lane]}}t.car.position.x=THREE.MathUtils.damp(t.car.position.x,t.target,1.4,dt);t.car.rotation.y=clamp((t.target-t.car.position.x)*.09,-.14,.14);t.indicator.visible=t.signal>0&&Math.sin(elapsed*12)>0;t.indicator.position.x=t.nextLane>t.lane?1:-1;t.car.position.z=t.z;
const dx=Math.abs(state.x-t.car.position.x),extent=2.20+t.car.userData.length*.46;const crossed=Math.min(oldZ,t.z)<extent&&Math.max(oldZ,t.z)>-extent;if(dx<t.car.userData.width+.79&&crossed)hit(state.speed>57?51:36,state.x>=t.car.position.x?1:-1);if(!t.passed&&oldZ<4&&t.z>=4){t.passed=true;if(dx>t.car.userData.width+.80&&dx<t.car.userData.width+1.6&&state.speed>33&&state.invuln===0){state.near++;const bonus=Math.round(300*state.mult);state.score+=bonus;state.nitro=Math.min(100,state.nitro+13);toast('NEAR MISS  +'+bonus);tone(880,.12,.07)}}for(const w of t.car.userData.wheels)w.spin.rotation.x-=t.speed*dt/.355;}
if(trafficCheck>2)trafficCheck=0;player.position.x=state.x;player.position.y=Math.sin(elapsed*18)*Math.min(state.speed/100,.6)*.008;player.rotation.y=lerp(player.rotation.y,-state.vx*.028-state.drift*steer*.08,1-Math.exp(-dt*7));player.userData.body.rotation.z=lerp(player.userData.body.rotation.z,-state.vx*.012,dt*7);player.userData.body.rotation.x=lerp(player.userData.body.rotation.x,clamp((state.speed-previousSpeed)/dt*.003,-.065,.04),dt*5);for(const w of player.userData.wheels){w.spin.rotation.x-=state.speed*dt/.355;if(w.front)w.pivot.rotation.y=lerp(w.pivot.rotation.y,-steer*.22,dt*10)}
state.gear=state.speed<-.5?-1:state.speed<.5?0:Math.min(6,1+Math.floor(state.speed/14));state.rpm=state.gear<=0?900:1800+((Math.abs(state.speed)%14)/14)*5000;if(state.gear!==lastGear){tone(65,.07,.1,'triangle');lastGear=state.gear}if(state.drift>.15&&Math.random()<dt*35)for(const s of[-1,1])emit(state.x+s,.18,1.6,'smoke');if(state.boost&&Math.random()<dt*45)for(const s of[-1,1])emit(state.x+s*.74,.34,2.6,'boost');if(!state.boost&&Math.random()<dt*5)emit(state.x+.74,.29,2.4,'smoke');if(state.time<=0)end('TIME UP / RUN COMPLETE');}
const look=new THREE.Vector3(),cameraTarget=new THREE.Vector3();function visuals(dt){for(const p of particles){if(p.life<=0)continue;p.life-=dt;p.mesh.visible=p.life>0;p.mesh.position.x+=p.vx*dt;p.mesh.position.y+=p.vy*dt;p.mesh.position.z+=(p.vz+Math.max(state.speed,0)*.75)*dt;p.mesh.material.opacity=Math.max(0,p.life/p.max)*(p.kind==='spark'?.9:.24);if(p.kind==='smoke')p.mesh.scale.addScalar(dt*.65);else if(p.kind==='spark')p.vy-=dt*12;}
if(state.mode==='menu'){const t=elapsed*.11;player.position.set(1.8,0,0);player.rotation.y=0;player.userData.body.rotation.set(0,0,0);camera.position.set(9.0+Math.sin(t)*1.6,3.15,7.7+Math.cos(t)*.65);camera.fov=48;look.set(-1.4,.8,-.4);camera.lookAt(look);traffic.forEach(t=>t.car.visible=false);gate.visible=false;}else{const wide=state.wide;cameraTarget.set(state.x*.77+(wide?1.15:.30),wide?4.1:2.9,wide?11.5:8.4);cameraTarget.y-=input.gas?.14:0;cameraTarget.z+=Math.max(0,state.speed-45)*.025;camera.position.lerp(cameraTarget,1-Math.exp(-dt*5));if(state.shake>0){camera.position.x+=(Math.random()-.5)*state.shake*.22;camera.position.y+=(Math.random()-.5)*state.shake*.16}camera.position.y+=Math.sin(elapsed*45)*Math.max(0,state.speed-55)*.0002;look.set(state.x*.70,1.0,-20-Math.max(state.speed,0)*.12);camera.lookAt(look);camera.fov=lerp(camera.fov,58+Math.max(0,state.speed-35)*.22+(state.boost?9:0),dt*3);gate.position.z=-(state.nextCP-state.distance);gate.visible=gate.position.z>-800;}
camera.updateProjectionMatrix();exhaust.forEach(f=>{f.visible=state.boost&&state.mode==='playing';f.scale.y=.75+Math.random()*.5});tailGlow.material.opacity=input.brake?.72:.32;for(const m of player.userData.brakeMaterials)m.color.set(input.brake?0xff5962:0xff1233);nitroGlow.material.opacity=state.boost?.55:0;ui.flash.style.opacity=state.shake*.29;ui.speedFX.style.opacity=state.boost?.8:clamp((state.speed-55)/100,0,.3);if(toastTime>0){toastTime-=dt;if(toastTime<=0)ui.toast.style.opacity=0}renderer.render(scene,camera);}
let hudTimer=0;function hud(dt){hudTimer+=dt;if(hudTimer<.065)return;hudTimer=0;ui.speed.textContent=Math.round(Math.abs(state.speed)*3.6);ui.gear.textContent=state.gear===-1?'R':state.gear===0?'N':state.gear;ui.score.textContent=String(Math.floor(state.score)).padStart(6,'0');ui.multiplier.textContent='×'+state.mult.toFixed(1);ui.timer.textContent=Math.max(0,state.time).toFixed(1);ui.timer.style.color=state.time<10?'#ff5d60':'#f3f5fa';ui.distance.innerHTML=(state.distance/1000).toFixed(2)+' <small>KM</small>';ui.rpmFill.style.width=(state.rpm/7000*100)+'%';ui.nitroFill.style.width=state.nitro+'%';ui.nitroText.textContent=Math.round(state.nitro)+'%';ui.checkpointDistance.textContent=Math.max(0,Math.ceil(state.nextCP-state.distance))+' M';ui.checkpointProgress.style.width=((state.distance%1400)/14)+'%';[...ui.health.children].forEach((e,i)=>e.style.background=state.health>i*33?'#d9ff43':'#ff3b4944');const zone=Math.floor(state.distance/600)%4;ui.zone.textContent=['MIDNIGHT CITY','PORT DISTRICT','NORTH TUNNEL','OUTER RING'][zone];}
let last=performance.now(),lastDraw=0;function loop(now){const realDt=(now-last)/1000;last=now;const dt=Math.min(realDt,.20);elapsed+=dt;frameMS=lerp(frameMS,realDt*1000,.02);let remain=dt;while(remain>0){const step=Math.min(remain,1/100);physics(step);remain-=step}if(!software||now-lastDraw>70){visuals(Math.min(dt,.10));lastDraw=now}hud(dt);updateAudio();requestAnimationFrame(loop)}
const keyMap={KeyW:'gas',ArrowUp:'gas',KeyS:'brake',ArrowDown:'brake',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'nitro'};addEventListener('keydown',e=>{if(keyMap[e.code]){if(state.mode==='playing'){e.preventDefault();input[keyMap[e.code]]=true}return}if(e.repeat)return;if(e.code==='Escape'){if(state.mode==='playing')showMode('paused');else if(state.mode==='paused')showMode('playing');else $('help').hidden=true}if(e.code==='KeyC')toggleCamera();if(e.code==='KeyR'&&state.mode!=='menu')reset();});addEventListener('keyup',e=>{if(keyMap[e.code]){input[keyMap[e.code]]=false;if(state.mode==='playing')e.preventDefault()}});addEventListener('blur',()=>{if(state.mode==='playing')showMode('paused');clearInput()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')showMode('paused');clearInput()});
function toggleCamera(){state.wide=!state.wide;$('cameraBtn').innerHTML='CAM <span>'+(state.wide?'02':'01')+'</span>';tone(440,.07,.04)}
$('startBtn').onclick=reset;$('restartBtn').onclick=reset;$('pauseRestart').onclick=reset;$('cameraBtn').onclick=toggleCamera;$('pauseBtn').onclick=()=>showMode('paused');$('resumeBtn').onclick=()=>{initAudio();showMode('playing')};$('helpBtn').onclick=()=>{$('help').hidden=false;initAudio();tone(330)};$('closeHelp').onclick=()=>{$('help').hidden=true;tone(440)};function menu(){showMode('menu');state.speed=0;state.boost=false;$('help').hidden=true}for(const id of['exitBtn','overMenu'])$(id).onclick=menu;$('brand').onclick=e=>{e.preventDefault();if(state.mode==='playing')showMode('paused')};$('soundBtn').onclick=()=>{initAudio();soundOn=!soundOn;if(audio)audio.master.gain.setTargetAtTime(soundOn?.42:0,audio.ctx.currentTime,.04);$('soundBtn').textContent='SOUND '+(soundOn?'ON':'OFF')};
for(const b of document.querySelectorAll('[data-control]')){const pointers=new Set();b.addEventListener('pointerdown',e=>{if(state.mode!=='playing')return;e.preventDefault();try{b.setPointerCapture(e.pointerId)}catch{}pointers.add(e.pointerId);input[b.dataset.control]=true;b.classList.add('held')});const release=e=>{pointers.delete(e.pointerId);if(!pointers.size){input[b.dataset.control]=false;b.classList.remove('held')}};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);b.addEventListener('contextmenu',e=>e.preventDefault())}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);$('touch').hidden=!(mobileUI()&&state.mode==='playing')});$('game').addEventListener('webglcontextlost',e=>{e.preventDefault();showMode('paused');$('loading').textContent='Graphics interrupted. Reload to resume racing.';$('loading').hidden=false});
// Read-only telemetry for repeatable gameplay verification.
window.erko={snapshot:()=>({...state,traffic:traffic.filter(t=>t.active).map(t=>({x:t.car.position.x,z:t.z,type:t.car.userData.type})),render:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,frameMS,software}})};
$('loading').hidden=true;requestAnimationFrame(loop);
const modelContext=document.modelContext;if(modelContext?.registerTool){for(const tool of[{name:'start_erko_ride',title:'Start ERKO RIDER',description:'Start a new racing run, resetting the current score.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{reset();return{mode:state.mode}}},{name:'read_erko_ride',title:'Read race status',description:'Read current racing status, score, speed, time and traffic.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>window.erko.snapshot()},{name:'pause_erko_ride',title:'Pause the ride',description:'Pause the current run.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state.mode==='playing')showMode('paused');return{mode:state.mode}}}])try{Promise.resolve(modelContext.registerTool(tool)).catch(()=>{})}catch{}}
